// <auto-generated />
namespace CurseDotNet.Class2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class agregar_tabla_productos1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregar_tabla_productos1));
        
        string IMigrationMetadata.Id
        {
            get { return "202010100427244_agregar_tabla_productos1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
